name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: evolpages
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: evol3d/evol
          path: evol
          ref: v0.2
      
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          # Path to Doxyfile
          doxyfile-path: evol/Doxyfile
          # Working directory
          working-directory: evol
      
      - name: Copy Docs
        run: |
          cp -r evol/.doxygen/html/* evolpages/evol/api/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate docs

          branch: master
          
          commit_options: '--no-verify --signoff'

          # Optional local file path to the repository
          # Defaults to the root of the repository
          repository: evol

          # Optional commit user and author settings
          commit_author: Robear Selwans <robear.selwans@outlook.com> # defaults to author of the commit that triggered the run

